[build]
cmd = """
cargo build &&
cp -r ./target/debug/bake ./bin/bake
"""

[[custom]]
name = "clean"
cmd = "cargo clean"
run = false

[[custom]]
name = "setup"
cmd = """
mkdir -p bin &&
rustup install stable &&
rustup default stable
"""
run = false

[[custom]]
name = "release"
cmd = """
cargo build --release &&
cp -r ./target/release/bake ./bin/bake
"""
run = false

[[custom]]
name = "docs"
cmd = "pandoc docs/baker.1.md -s -t man -o docs/baker.1"
run = false

[[pre]]
name = "fmt"
cmd = "cargo fmt"
